network:
  version: 2
  ethernets:
    eth0:
      renderer: NetworkManager
      match: {}
      addresses:
      - "10.11.96.150/24"
      networkmanager:
        uuid: "75a1216a-9d1a-30cd-8aca-ace5526ec021"
        name: "netplan-eth0"
        passthrough:
          proxy._: ""
