#ifndef UDPRX_H_INCLUDED
#define UDPRX_H_INCLUDED
#include "dasio/interface.h"
#include "dasio/tm_client.h"

using namespace DAS_IO;

class UDPrx : public Interface {
  public:
    UDPrx();
    bool protocol_input();
  private:
    /**
     * Binds fd to listen on the specified UDP port
     * @param port UDP port to listen on
     */
    void Bind(int port);
    int fillbuf();
    // int not_ndigits(int n, int &value);
    // int not_ISO8601(double *Time);
    // int not_nfloat(float *value);
};

class UDPrxext_tm_client : public tm_client {
  public:
    inline UDPrxext_tm_client(int bufsize, bool fast) :
      tm_client(bufsize, fast) {}
    /**
     * Sets up interfaces to the radio, [ TM_sndr,
     * and Cmd_reader]
     */
    void adopted();
  protected:
    /** Generated by TMC */
    unsigned int process_data();
    void process_quit();
    void send_row(uint16_t MFCtr, const uint8_t *raw);
};

#endif
