function pmoudiahkstale(varargin);
% pmoudiahkstale( [...] );
% Alicat HK Stale
h = timeplot({'MMFC_Stale','Alicat_Stale'}, ...
      'Alicat HK Stale', ...
      'Stale', ...
      {'MMFC\_Stale','Alicat\_Stale'}, ...
      varargin{:} );
