function pmoudiattitudess(varargin);
% pmoudiattitudess( [...] );
% Attitude Side Slip
h = timeplot({'Side_slip'}, ...
      'Attitude Side Slip', ...
      'Side Slip', ...
      {'Side\_slip'}, ...
      varargin{:} );
