function pmoudidacsaais(varargin);
% pmoudidacsaais( [...] );
% uDACS A AI Stat
h = timeplot({'uDACS_A_status'}, ...
      'uDACS A AI Stat', ...
      'AI Stat', ...
      {'uDACS\_A\_status'}, ...
      varargin{:} );
