function pmoudiattitudesz(varargin);
% pmoudiattitudesz( [...] );
% Attitude SZ
h = timeplot({'Solar_Zenith','Sun_Elev_AC'}, ...
      'Attitude SZ', ...
      'SZ', ...
      {'Solar\_Zenith','Sun\_Elev\_AC'}, ...
      varargin{:} );
