function pmoudialicatccm(varargin);
% pmoudialicatccm( [...] );
% Alicat ccm
h = timeplot({'MMFC_Set','MMFC_VolFlow'}, ...
      'Alicat ccm', ...
      'ccm', ...
      {'MMFC\_Set','MMFC\_VolFlow'}, ...
      varargin{:} );
