function pmoudialicatccm(varargin);
% pmoudialicatccm( [...] );
% Alicat ccm
h = timeplot({'MMFC_VolFlow','MMFC_Set'}, ...
      'Alicat ccm', ...
      'ccm', ...
      {'MMFC\_VolFlow','MMFC\_Set'}, ...
      varargin{:} );
