function pmoudidacsaain(varargin);
% pmoudidacsaain( [...] );
% uDACS A AI N
h = timeplot({'uDACS_A_N'}, ...
      'uDACS A AI N', ...
      'AI N', ...
      {'uDACS\_A\_N'}, ...
      varargin{:} );
