function pmoudialicatnccm(varargin);
% pmoudialicatnccm( [...] );
% Alicat nccm
h = timeplot({'MMFC_MassFlow'}, ...
      'Alicat nccm', ...
      'nccm', ...
      {'MMFC\_MassFlow'}, ...
      varargin{:} );
