function pmoudialicatnccm(varargin);
% pmoudialicatnccm( [...] );
% Alicat nccm
h = timeplot({'MMFC_Set','MMFC_MassFlow'}, ...
      'Alicat nccm', ...
      'nccm', ...
      {'MMFC\_Set','MMFC\_MassFlow'}, ...
      varargin{:} );
