function pmoudiahks(varargin);
% pmoudiahks( [...] );
% Alicat HK Status
h = timeplot({'MMFC_Status'}, ...
      'Alicat HK Status', ...
      'Status', ...
      {'MMFC\_Status'}, ...
      varargin{:} );
